@echo off
set PATH=C:\Program Files\nodejs;%PATH%
echo Đang cài đặt thư viện...
call npm install
echo Đang khởi động trình duyệt...
start http://localhost:5173
echo Đang chạy server...
call npm run dev
